/**
 * Knowledge Graph Command — CLI for querying codebase knowledge graphs.
 *
 * Subcommands: stats, query, explain, path, diff, diff-wiki, search, context
 *
 * Operates on `.workflow/codebase/knowledge-graph.json` generated by
 * compatible code analyzers.
 */

import type { Command } from 'commander';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { execSync } from 'node:child_process';
import type { KnowledgeGraph } from '../graph/types.js';
import { loadGraph } from '../graph/loader.js';
import { searchNodes, findPath, diffChanges, countBy, truncate } from '../graph/query.js';
import { FsAnalyzer } from '../graph/analyzers/fs-analyzer.js';
import { DatabaseConnection, getDatabasePath, QueryBuilder } from '../graph/db/index.js';
import { GraphTraverser } from '../graph/traversal.js';
import { GraphQueryManager } from '../graph/graph-queries.js';
import { FileWatcher } from '../graph/sync/watcher.js';
import { parseQuery } from '../graph/search/query-parser.js';
import { migrateJsonToSqlite, exportSqliteToJson } from '../graph/migration.js';

import { WikiIndexer } from '#maestro-dashboard/wiki/wiki-indexer.js';
import type { WikiEntry } from '#maestro-dashboard/wiki/wiki-types.js';

function loadGraphOrExit(): KnowledgeGraph {
  try {
    return loadGraph();
  } catch (err) {
    console.error((err as Error).message);
    console.error('  Hint: generate one with a compatible code analyzer');
    process.exit(1);
  }
}

// ── Wiki cross-reference ──────────────────────────────────────────────

let _wikiIndexer: WikiIndexer | null = null;
function getWikiIndexer(): WikiIndexer | null {
  if (_wikiIndexer) return _wikiIndexer;
  const workflowRoot = resolve('.workflow');
  if (!existsSync(workflowRoot)) return null;
  _wikiIndexer = new WikiIndexer({ workflowRoot });
  return _wikiIndexer;
}

interface WikiMatch {
  id: string;
  type: string;
  title: string;
  matchReason: string;
}

async function findRelatedWikiEntries(nodeId: string, filePath?: string): Promise<WikiMatch[]> {
  const indexer = getWikiIndexer();
  if (!indexer) return [];
  try {
    const index = await indexer.get();
    const matches: WikiMatch[] = [];
    const seen = new Set<string>();

    for (const e of index.entries) {
      if (seen.has(e.id)) continue;
      if (e.ext?.virtualKind === 'kg-node' && e.ext?.kgNodeId === nodeId) {
        seen.add(e.id);
        matches.push({ id: e.id, type: e.type, title: e.title, matchReason: 'kg-node-entry' });
        continue;
      }
      if (filePath && Array.isArray(e.ext?.codeLocations)) {
        const locs = e.ext.codeLocations as string[];
        const normFp = filePath.replace(/\\/g, '/').toLowerCase();
        if (locs.some(l => l.replace(/\\/g, '/').toLowerCase() === normFp)) {
          seen.add(e.id);
          matches.push({ id: e.id, type: e.type, title: e.title, matchReason: 'codePath-match' });
        }
      }
      if (seen.has(e.id)) continue;
      if (filePath && Array.isArray(e.ext?.codePaths)) {
        const paths = e.ext.codePaths as string[];
        const normFp = filePath.replace(/\\/g, '/').toLowerCase();
        if (paths.some(p => p.replace(/\\/g, '/').toLowerCase() === normFp)) {
          seen.add(e.id);
          matches.push({ id: e.id, type: e.type, title: e.title, matchReason: 'codePath-match' });
        }
      }
    }
    return matches;
  } catch {
    return [];
  }
}

// ── SQLite helpers ────────────────────────────────────────────────────

function openSqliteOrExit(): { conn: DatabaseConnection; queries: QueryBuilder } {
  const dbPath = getDatabasePath();
  if (!existsSync(dbPath)) {
    console.error(`SQLite graph not found: ${dbPath}`);
    console.error('  Hint: legacy commands require a SQLite index (from older maestro versions)');
    process.exit(1);
  }
  const conn = new DatabaseConnection();
  conn.open(dbPath);
  return { conn, queries: new QueryBuilder(conn) };
}

function hasSqliteDb(): boolean {
  return existsSync(getDatabasePath());
}

// ── MaestroGraph helpers ─────────────────────────────────────────────────

async function requireCodeGraph(): Promise<{ adapter: any }> {
  const { MaestroGraph } = await import('../graph/kg/engine.js');
  if (!MaestroGraph.isInitialized(resolve('.'))) {
    console.error('MaestroGraph not initialized for this project.');
    console.error('  Run: maestro kg sync');
    process.exit(1);
  }
  const mg = await MaestroGraph.open(resolve('.'));
  const adapter = {
    searchNodes: (q: string, opts?: { limit?: number }) => mg.searchCode(q, opts),
    resolveNode: (id: string) => mg.getNode(id),
    getCallers: (id: string, d?: number) => mg.getCallers(id, d),
    getCallees: (id: string, d?: number) => mg.getCallees(id, d),
    getNodesInFile: (fp: string) => mg.getQueryBuilder().getNodesByFile(fp),
    stats: () => mg.getStats(),
    close: () => mg.close(),
  };
  return { adapter };
}

// ── Registration ───────────────────────────────────────────────────────

export function registerKgCommand(program: Command): void {
  const kg = program
    .command('kg')
    .description('Query codebase knowledge graph (CodeGraph engine)');

  // ── stats ──────────────────────────────────────────────────────────
  kg
    .command('stats')
    .description('Display knowledge graph statistics')
    .option('--json', 'Output as JSON')
    .action((_opts) => {
      const graph = loadGraphOrExit();
      const nodesByType = countBy(graph.nodes, n => n.type);
      const edgesByType = countBy(graph.edges, e => e.type);

      const data = {
        project: graph.project.name,
        version: graph.version,
        nodes: { total: graph.nodes.length, byType: nodesByType },
        edges: { total: graph.edges.length, byType: edgesByType },
        layers: graph.layers.length,
        tourSteps: graph.tour.length,
      };

      if (_opts.json) {
        console.log(JSON.stringify(data, null, 2));
        return;
      }

      console.log(`Knowledge Graph: ${data.project} (v${data.version})`);
      console.log('');
      console.log(`Nodes: ${data.nodes.total}`);
      for (const [type, count] of Object.entries(nodesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Edges: ${data.edges.total}`);
      for (const [type, count] of Object.entries(edgesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Layers: ${data.layers}`);
      console.log(`Tour steps: ${data.tourSteps}`);
    });

  // ── query ──────────────────────────────────────────────────────────
  kg
    .command('query <text>')
    .description('Search nodes by name, summary, or tags (code + knowledge)')
    .option('--limit <n>', 'Max results', '10')
    .option('--type <nodeType>', 'Filter by node type')
    .option('--json', 'Output as JSON')
    .action(async (text: string, opts) => {
      const limit = Math.min(Number(opts.limit) || 10, 500);

      // MaestroGraph unified search (code + knowledge)
      try {
        const { MaestroGraph } = await import('../graph/kg/engine.js');
        const { parseQuery: parseMgQuery } = await import('../graph/kg/query/search.js');
        if (MaestroGraph.isInitialized(resolve('.'))) {
          const mg = await MaestroGraph.open(resolve('.'));
          try {
            const mgParsed = parseMgQuery(text);
            const effectiveText = mgParsed.text || text;
            const sourceTypes = mgParsed.sourceTypes?.length > 0 ? mgParsed.sourceTypes : undefined;
            const kinds = mgParsed.kinds?.length > 0 ? mgParsed.kinds : undefined;
            const output = mg.searchUnified(effectiveText, { limit, sourceTypes: sourceTypes as any, kinds: kinds as any }); // eslint-disable-line @typescript-eslint/no-explicit-any

            const codeResults = output.directMatches.filter(r => r.node.sourceType === 'codegraph');
            const knowledgeResults = output.directMatches.filter(r => r.node.sourceType !== 'codegraph');

            if (opts.json) {
              console.log(JSON.stringify({ query: text, codeResults: codeResults.map(r => r.node), knowledgeResults: knowledgeResults.map(r => ({ ...r.node, score: r.score })) }, null, 2));
              return;
            }

            console.log(`Query: "${text}"  (${codeResults.length} code + ${knowledgeResults.length} knowledge)`);
            for (const r of codeResults) {
              const n = r.node;
              const desc = n.signature ? truncate(n.signature, 60) : `${n.kind} "${n.name}" in ${n.filePath}`;
              console.log(`  [${n.kind}] ${n.id} -- ${desc}  (${r.score.toFixed(1)})`);
            }
            for (const r of knowledgeResults) {
              const n = r.node;
              const def = n.definition ? ` — ${truncate(n.definition, 60)}` : '';
              console.log(`  [${n.sourceType}:${n.kind}] ${n.name}${def}  (${r.score.toFixed(1)})`);
            }
            return;
          } finally {
            mg.close();
          }
        }
      } catch { /* MaestroGraph not available */ }

      // Legacy fallback: old SQLite or JSON graph
      if (hasSqliteDb()) {
        const { conn, queries } = openSqliteOrExit();
        try {
          const parsed = parseQuery(text);
          const results = queries.searchNodes(parsed.text || text, { limit });
          console.log(`Query: "${text}"  (${results.length} results, legacy SQLite)`);
          for (const n of results) {
            console.log(`  [${n.kind}] ${n.id} -- ${n.name}`);
          }
        } finally {
          conn.close();
        }
      } else {
        const graph = loadGraphOrExit();
        const matches = searchNodes(graph, text, { limit, type: opts.type });
        console.log(`Query: "${text}"  (${matches.length} results, JSON)`);
        for (const n of matches) {
          console.log(`  [${n.type}] ${n.id} -- ${truncate(n.summary, 80)}`);
        }
      }
    });

  // ── explain ────────────────────────────────────────────────────────
  kg
    .command('explain <node-id>')
    .description('Show full details of a node and its connections')
    .option('--json', 'Output as JSON')
    .option('--no-wiki', 'Skip wiki cross-reference lookup')
    .action(async (nodeId: string, opts) => {
      const graph = loadGraphOrExit();
      const node = graph.nodes.find(n => n.id === nodeId);

      if (!node) {
        console.error(`Node not found: ${nodeId}`);
        process.exit(1);
      }

      const incoming = graph.edges.filter(e => e.target === nodeId);
      const outgoing = graph.edges.filter(e => e.source === nodeId);
      const layers = graph.layers.filter(l => l.nodeIds.includes(nodeId));

      const wikiMatches = opts.wiki !== false
        ? await findRelatedWikiEntries(nodeId, node.filePath)
        : [];

      if (opts.json) {
        console.log(JSON.stringify({ node, incoming, outgoing, layers, wiki: wikiMatches }, null, 2));
        return;
      }

      console.log(`Node: ${node.id}`);
      console.log(`  Type:       ${node.type}`);
      console.log(`  Name:       ${node.name}`);
      if (node.filePath) console.log(`  File:       ${node.filePath}`);
      console.log(`  Summary:    ${node.summary}`);
      if (node.tags?.length) console.log(`  Tags:       ${node.tags.join(', ')}`);
      if (node.complexity) console.log(`  Complexity: ${node.complexity}`);

      if (layers.length > 0) {
        console.log('');
        console.log('Layers:');
        for (const l of layers) {
          console.log(`  ${l.id} -- ${l.name}`);
        }
      }

      if (incoming.length > 0) {
        console.log('');
        console.log(`Incoming edges (${incoming.length}):`);
        for (const e of incoming) {
          console.log(`  ${e.source} --${e.type}--> ${nodeId}`);
        }
      }

      if (outgoing.length > 0) {
        console.log('');
        console.log(`Outgoing edges (${outgoing.length}):`);
        for (const e of outgoing) {
          console.log(`  ${nodeId} --${e.type}--> ${e.target}`);
        }
      }

      if (wikiMatches.length > 0) {
        console.log('');
        console.log(`Related wiki entries (${wikiMatches.length}):`);
        for (const w of wikiMatches) {
          console.log(`  [${w.type}] ${w.id} -- ${w.title} (${w.matchReason})`);
        }
      }
    });

  // ── path ───────────────────────────────────────────────────────────
  kg
    .command('path <from-id> <to-id>')
    .description('Find shortest path between two nodes (BFS, undirected)')
    .option('--json', 'Output as JSON')
    .action((fromId: string, toId: string, opts) => {
      const graph = loadGraphOrExit();

      try {
        const result = findPath(graph, fromId, toId);

        if (!result.found) {
          if (opts.json) {
            console.log(JSON.stringify({ from: fromId, to: toId, path: null, message: 'No path found' }, null, 2));
          } else {
            console.log(`No path found from ${fromId} to ${toId}`);
          }
          return;
        }

        if (opts.json) {
          console.log(JSON.stringify({ from: fromId, to: toId, length: result.length, steps: result.steps }, null, 2));
          return;
        }

        console.log(`Path: ${fromId} -> ${toId}  (${result.length} hops)`);
        console.log('');
        for (let i = 0; i < result.steps.length; i++) {
          const step = result.steps[i];
          console.log(`  [${step.type ?? '?'}] ${step.node} -- ${truncate(step.name ?? '', 60)}`);
          if (step.edgeToNext) {
            console.log(`    | ${step.edgeToNext}`);
          }
        }
      } catch (err) {
        console.error((err as Error).message);
        process.exit(1);
      }
    });

  // ── diff ───────────────────────────────────────────────────────────
  kg
    .command('diff')
    .description('Show KG nodes affected by git changes')
    .option('--staged', 'Use staged changes only')
    .option('--json', 'Output as JSON')
    .action((opts) => {
      const graph = loadGraphOrExit();

      let changedFiles: string[];
      try {
        const cmd = opts.staged
          ? 'git diff --staged --name-only'
          : 'git diff --name-only';
        const output = execSync(cmd, { encoding: 'utf-8' }).trim();
        changedFiles = output ? output.split('\n').map(f => f.trim()).filter(Boolean) : [];
      } catch {
        console.error('Failed to run git diff. Are you in a git repository?');
        process.exit(1);
      }

      if (changedFiles.length === 0) {
        if (opts.json) {
          console.log(JSON.stringify({ changedFiles: [], direct: [], impacted: [] }, null, 2));
        } else {
          console.log('No changed files detected.');
        }
        return;
      }

      const result = diffChanges(graph, changedFiles);

      if (opts.json) {
        console.log(JSON.stringify(result, null, 2));
        return;
      }

      console.log(`Changed files: ${changedFiles.length}`);
      console.log('');

      console.log(`Direct (${result.direct.length}):`);
      if (result.direct.length === 0) {
        console.log('  (no KG nodes match changed files)');
      } else {
        for (const n of result.direct) {
          console.log(`  [${n.type}] ${n.id} -- ${truncate(n.summary, 60)}`);
        }
      }

      console.log('');
      console.log(`Impacted (${result.impacted.length}):`);
      if (result.impacted.length === 0) {
        console.log('  (no 1-hop neighbors found)');
      } else {
        for (const n of result.impacted) {
          console.log(`  [${n.type}] ${n.id} -- ${truncate(n.summary, 60)}`);
        }
      }
    });

  // ── diff-wiki ─────────────────────────────────────────────────────
  kg
    .command('diff-wiki')
    .description('Cross-reference git changes with KG nodes and wiki entries')
    .option('--staged', 'Use staged changes only')
    .option('--json', 'Output as JSON')
    .action(async (opts) => {
      const graph = loadGraphOrExit();

      let changedFiles: string[];
      try {
        const cmd = opts.staged
          ? 'git diff --staged --name-only'
          : 'git diff --name-only';
        const output = execSync(cmd, { encoding: 'utf-8' }).trim();
        changedFiles = output ? output.split('\n').map(f => f.trim()).filter(Boolean) : [];
      } catch {
        console.error('Failed to run git diff. Are you in a git repository?');
        process.exit(1);
      }

      if (changedFiles.length === 0) {
        if (opts.json) {
          console.log(JSON.stringify({ changedFiles: [], affectedWiki: [] }, null, 2));
        } else {
          console.log('No changed files detected.');
        }
        return;
      }

      const result = diffChanges(graph, changedFiles);

      // Collect all affected file paths from KG nodes
      const affectedPaths = new Set<string>();
      for (const n of result.direct) {
        if (n.filePath) affectedPaths.add(n.filePath.replace(/\\/g, '/').toLowerCase());
      }
      for (const n of result.impacted) {
        if (n.filePath) affectedPaths.add(n.filePath.replace(/\\/g, '/').toLowerCase());
      }
      for (const f of changedFiles) {
        affectedPaths.add(f.replace(/\\/g, '/').toLowerCase());
      }

      // Cross-reference with wiki
      const indexer = getWikiIndexer();
      const affectedWiki: Array<{ id: string; type: string; title: string; reason: string }> = [];

      if (indexer) {
        try {
          const index = await indexer.get();
          const seen = new Set<string>();
          for (const entry of index.entries) {
            if (seen.has(entry.id)) continue;
            if (Array.isArray(entry.ext?.codeLocations)) {
              const locs = entry.ext.codeLocations as string[];
              for (const loc of locs) {
                if (affectedPaths.has(loc.replace(/\\/g, '/').toLowerCase())) {
                  seen.add(entry.id);
                  affectedWiki.push({ id: entry.id, type: entry.type, title: entry.title, reason: 'codeLocation' });
                  break;
                }
              }
            }
            if (seen.has(entry.id)) continue;
            if (Array.isArray(entry.ext?.codePaths)) {
              const paths = entry.ext.codePaths as string[];
              for (const p of paths) {
                if (affectedPaths.has(p.replace(/\\/g, '/').toLowerCase())) {
                  seen.add(entry.id);
                  affectedWiki.push({ id: entry.id, type: entry.type, title: entry.title, reason: 'codePath' });
                  break;
                }
              }
            }
          }
        } catch { /* wiki unavailable — continue without */ }
      }

      if (opts.json) {
        console.log(JSON.stringify({
          changedFiles,
          directNodes: result.direct.length,
          impactedNodes: result.impacted.length,
          affectedWiki,
        }, null, 2));
        return;
      }

      console.log(`Changed files: ${changedFiles.length}`);
      console.log(`KG direct: ${result.direct.length}, impacted: ${result.impacted.length}`);
      console.log('');

      if (affectedWiki.length === 0) {
        console.log('No wiki entries affected by these changes.');
      } else {
        console.log(`Affected wiki entries (${affectedWiki.length}):`);
        for (const w of affectedWiki) {
          console.log(`  [${w.type}] ${w.id} -- ${w.title} (${w.reason})`);
        }
      }
    });

  // ── index ─────────────────────────────────────────────────────────
  kg
    .command('index')
    .description('Scan codebase and generate knowledge graph (CodeGraph)')
    .option('--src <path>', 'Source directory to scan', 'src')
    .option('--json', 'Output stats as JSON after indexing')
    .action(async (opts) => {
      const srcPath = resolve(opts.src);
      if (!existsSync(srcPath)) {
        console.error(`Source directory not found: ${srcPath}`);
        process.exit(1);
      }

      // MaestroGraph tree-sitter engine
      try {
        const { MaestroGraph } = await import('../graph/kg/engine.js');
        console.log('Using MaestroGraph tree-sitter engine...');
        const projectRoot = resolve('.');
        const mg = MaestroGraph.isInitialized(projectRoot)
          ? await MaestroGraph.open(projectRoot)
          : await MaestroGraph.init(projectRoot);
        try {
          const results = await mg.sync();
          const stats = mg.getStats();
          const totalDuration = results.reduce((sum, r) => sum + r.durationMs, 0);

          if (opts.json) {
            console.log(JSON.stringify({ ...stats, results, engine: 'maestrograph' }, null, 2));
            return;
          }

          console.log('');
          console.log(`Nodes: ${stats.nodeCount}`);
          for (const [kind, count] of Object.entries(stats.nodesByKind)) {
            console.log(`  ${kind}: ${count}`);
          }
          console.log('');
          console.log(`Edges: ${stats.edgeCount}`);
          for (const [kind, count] of Object.entries(stats.edgesByKind)) {
            console.log(`  ${kind}: ${count}`);
          }
          console.log('');
          console.log(`Files: ${stats.fileCount}`);
          console.log(`DB size: ${(stats.dbSizeBytes / 1024).toFixed(1)} KB`);
          console.log(`Duration: ${totalDuration}ms`);
          for (const r of results) {
            console.log(`  ${r.source}: +${r.nodesAdded} -${r.nodesRemoved} nodes, +${r.edgesAdded} edges (${r.durationMs}ms)`);
          }
          return;
        } finally {
          mg.close();
        }
      } catch (mgErr) {
        if (process.env.DEBUG) {
          console.error('MaestroGraph error:', mgErr instanceof Error ? mgErr.message : mgErr);
        }
        console.error('MaestroGraph engine failed. Falling back to JSON analyzer...');
        console.error('');
      }

      // JSON mode (legacy)
      const analyzer = new FsAnalyzer();
      console.log(`Scanning ${srcPath} ...`);

      const graph = await analyzer.analyze(srcPath);

      // If scanning a subdirectory, try to pick up project name from CWD
      const cwdPkg = resolve('package.json');
      if (existsSync(cwdPkg) && srcPath !== resolve('.')) {
        try {
          const pkg = JSON.parse(readFileSync(cwdPkg, 'utf-8'));
          if (pkg.name) graph.project.name = pkg.name;
          // Also pick up frameworks from root package.json
          const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
          const fwChecks: [string, string][] = [
            ['react', 'React'], ['vue', 'Vue'], ['angular', 'Angular'],
            ['express', 'Express'], ['fastify', 'Fastify'], ['next', 'Next.js'],
            ['nuxt', 'Nuxt'], ['commander', 'Commander'], ['ink', 'Ink'],
          ];
          const frameworks: string[] = [];
          for (const [dep, name] of fwChecks) {
            if (allDeps?.[dep]) frameworks.push(name);
          }
          if (frameworks.length > 0) graph.project.frameworks = frameworks;
        } catch { /* ignore */ }
      }

      // Ensure output directory exists
      const outDir = resolve('.workflow', 'codebase');
      mkdirSync(outDir, { recursive: true });

      const outPath = resolve(outDir, 'knowledge-graph.json');
      writeFileSync(outPath, JSON.stringify(graph, null, 2), 'utf-8');

      // Collect stats
      const nodesByType: Record<string, number> = {};
      for (const n of graph.nodes) {
        nodesByType[n.type] = (nodesByType[n.type] ?? 0) + 1;
      }
      const edgesByType: Record<string, number> = {};
      for (const e of graph.edges) {
        edgesByType[e.type] = (edgesByType[e.type] ?? 0) + 1;
      }

      const stats = {
        project: graph.project.name,
        languages: graph.project.languages,
        frameworks: graph.project.frameworks,
        nodes: { total: graph.nodes.length, byType: nodesByType },
        edges: { total: graph.edges.length, byType: edgesByType },
        layers: graph.layers.length,
        tourSteps: graph.tour.length,
        output: outPath,
      };

      if (opts.json) {
        console.log(JSON.stringify(stats, null, 2));
        return;
      }

      console.log('');
      console.log(`Project: ${stats.project}`);
      console.log(`Languages: ${stats.languages.join(', ') || 'none detected'}`);
      if (stats.frameworks.length > 0) {
        console.log(`Frameworks: ${stats.frameworks.join(', ')}`);
      }
      console.log('');
      console.log(`Nodes: ${stats.nodes.total}`);
      for (const [type, count] of Object.entries(nodesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Edges: ${stats.edges.total}`);
      for (const [type, count] of Object.entries(edgesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Layers: ${stats.layers}`);
      console.log(`Tour steps: ${stats.tourSteps}`);
      console.log('');
      console.log(`Written to: ${outPath}`);
    });

  // ── sync (incremental) ────────────────────────────────────────────
  kg
    .command('sync')
    .description('Incremental sync — only re-index changed files (CodeGraph)')
    .option('--json', 'Output as JSON')
    .action(async (opts) => {
      const { adapter } = await requireCodeGraph();
      try {
        const result = await adapter.sync();
        if (opts.json) {
          console.log(JSON.stringify({ ...result, engine: 'codegraph' }, null, 2));
        } else {
          const changed = result.filesAdded + result.filesModified + result.filesRemoved;
          console.log(`Sync complete: ${changed} files changed (${result.filesAdded} added, ${result.filesModified} modified, ${result.filesRemoved} removed), ${result.nodesUpdated} nodes updated (${result.durationMs}ms)`);
        }
      } finally {
        adapter.close();
      }
    });

  // ── watch ──────────────────────────────────────────────────────────
  kg
    .command('watch')
    .description('Watch for file changes and auto-sync (CodeGraph)')
    .option('--debounce <ms>', 'Debounce delay in milliseconds', '2000')
    .action(async (opts) => {
      const { adapter } = await requireCodeGraph();
      try {
        const projectRoot = resolve('.');
        const debounceMs = Number(opts.debounce) || 2000;

        const watcher = new FileWatcher(
          projectRoot,
          async () => {
            const result = await adapter.sync();
            const filesChanged = result.filesAdded + result.filesModified + result.filesRemoved;
            return { filesChanged, durationMs: result.durationMs };
          },
          {
            debounceMs,
            onSyncComplete: (result) => {
              if (result.filesChanged > 0) {
                console.log(`[sync] ${result.filesChanged} files updated (${result.durationMs}ms)`);
              }
            },
            onSyncError: (err) => {
              console.error(`[sync error] ${err.message}`);
            },
          },
        );

        const started = watcher.start();
        if (!started) {
          console.error('Could not start file watcher (unsupported filesystem?)');
          adapter.close();
          process.exit(1);
        }

        console.log(`Watching for changes (debounce: ${debounceMs}ms) — press Ctrl+C to stop`);

        process.on('SIGINT', () => {
          watcher.stop();
          adapter.close();
          console.log('\nWatcher stopped.');
          process.exit(0);
        });
      } catch (err) {
        adapter.close();
        throw err;
      }
    });

  // ── callers ────────────────────────────────────────────────────────
  kg
    .command('callers <node-id>')
    .description('Show callers of a function/method (CodeGraph)')
    .option('--depth <n>', 'Max traversal depth', '2')
    .option('--json', 'Output as JSON')
    .action(async (nodeId: string, opts) => {
      const depth = Number(opts.depth) || 2;
      const { adapter } = await requireCodeGraph();
      try {
        const callers = await adapter.getCallers(nodeId, depth);
        if (opts.json) {
          console.log(JSON.stringify(callers.map((c: any) => ({ // eslint-disable-line @typescript-eslint/no-explicit-any
            id: c.node.id, kind: c.node.kind, name: c.node.name,
            filePath: c.node.filePath, edgeKind: c.edge?.kind ?? 'calls',
          })), null, 2));
          return;
        }
        console.log(`Callers of ${nodeId} (${callers.length}):`);
        for (const { node, edge } of callers) {
          console.log(`  [${node.kind}] ${node.id} --${edge?.kind ?? 'calls'}-->`);
          if (node.signature) console.log(`    ${node.signature}`);
        }
      } finally {
        adapter.close();
      }
    });

  // ── callees ────────────────────────────────────────────────────────
  kg
    .command('callees <node-id>')
    .description('Show callees of a function/method (CodeGraph)')
    .option('--depth <n>', 'Max traversal depth', '2')
    .option('--json', 'Output as JSON')
    .action(async (nodeId: string, opts) => {
      const depth = Number(opts.depth) || 2;
      const { adapter } = await requireCodeGraph();
      try {
        const callees = await adapter.getCallees(nodeId, depth);
        if (opts.json) {
          console.log(JSON.stringify(callees.map((c: any) => ({ // eslint-disable-line @typescript-eslint/no-explicit-any
            id: c.node.id, kind: c.node.kind, name: c.node.name,
            filePath: c.node.filePath, edgeKind: c.edge?.kind ?? 'calls',
          })), null, 2));
          return;
        }
        console.log(`Callees of ${nodeId} (${callees.length}):`);
        for (const { node, edge } of callees) {
          console.log(`  --${edge?.kind ?? 'calls'}--> [${node.kind}] ${node.id}`);
          if (node.signature) console.log(`    ${node.signature}`);
        }
      } finally {
        adapter.close();
      }
    });

  // ── search ─────────────────────────────────────────────────────────
  kg
    .command('search <text>')
    .description('Search nodes with optional context and wiki cross-references (CodeGraph)')
    .option('--context', 'Include caller/callee counts for each result')
    .option('--wiki', 'Include related wiki entries for each result')
    .option('--kind <types>', 'Filter by node kind (comma-separated: function,class,interface,method,type_alias,const)')
    .option('--limit <n>', 'Max results', '10')
    .option('--json', 'Output as JSON')
    .action(async (text: string, opts) => {
      const limit = Math.min(Number(opts.limit) || 10, 500);
      const kinds = opts.kind ? (opts.kind as string).split(',').map((s: string) => s.trim()).filter(Boolean) : undefined;
      const { adapter } = await requireCodeGraph();
      try {
        // Multi-kind: query each kind separately and merge, because the
        // upstream CodeGraph API may not support multiple kinds in one call.
        let cgResults: Array<{ node?: any; score?: number } & Record<string, any>>; // eslint-disable-line @typescript-eslint/no-explicit-any
        if (kinds && kinds.length > 1) {
          const seen = new Set<string>();
          const merged: typeof cgResults = [];
          for (const k of kinds) {
            const partial = await adapter.searchNodes(text, { limit, kinds: [k] });
            for (const r of partial) {
              const id = (r.node ?? r).id;
              if (!seen.has(id)) { seen.add(id); merged.push(r); }
            }
          }
          merged.sort((a, b) => ((b.score ?? 0) - (a.score ?? 0)));
          cgResults = merged.slice(0, limit);
        } else {
          cgResults = await adapter.searchNodes(text, { limit, kinds });
        }

        const enriched: Array<{
          id: string; kind: string; name: string; filePath: string;
          signature?: string; isExported?: boolean;
          score?: number;
          callerCount?: number; calleeCount?: number;
          wiki?: WikiMatch[];
        }> = [];

        for (const r of cgResults) {
          const n = r.node ?? r;
          const entry: typeof enriched[number] = {
            id: n.id, kind: n.kind, name: n.name, filePath: n.filePath,
            signature: n.signature || undefined,
            isExported: n.isExported || undefined,
            score: typeof r.score === 'number' ? r.score : undefined,
          };

          if (opts.context) {
            const callers = await adapter.getCallers(n.id, 1);
            const callees = await adapter.getCallees(n.id, 1);
            entry.callerCount = callers.length;
            entry.calleeCount = callees.length;
          }

          if (opts.wiki) {
            entry.wiki = await findRelatedWikiEntries(n.id, n.filePath);
          }

          enriched.push(entry);
        }

        if (opts.json) {
          console.log(JSON.stringify({ query: text, total: enriched.length, nodes: enriched, engine: 'codegraph' }, null, 2));
          return;
        }

        console.log(`Search: "${text}"  (${enriched.length} results, CodeGraph)`);
        for (const n of enriched) {
          const exported = n.isExported ? 'Exported ' : '';
          const desc = n.signature ? truncate(n.signature, 60) : `${exported}${n.kind} "${n.name}" in ${n.filePath}`;
          let line = `  [${n.kind}] ${n.id} -- ${desc}`;
          if (n.callerCount !== undefined) {
            line += `  (callers: ${n.callerCount}, callees: ${n.calleeCount})`;
          }
          if (n.score !== undefined) {
            line += `  (score: ${n.score.toFixed(2)})`;
          }
          console.log(line);
          if (n.wiki && n.wiki.length > 0) {
            for (const w of n.wiki) {
              console.log(`    wiki: [${w.type}] ${w.id} -- ${w.title} (${w.matchReason})`);
            }
          }
        }
      } finally {
        adapter.close();
      }
    });

  // ── context ──────────────────────────────────────────────────────
  kg
    .command('context <node-id>')
    .description('Show full context: callers, callees, file siblings, and wiki (CodeGraph)')
    .option('--depth <n>', 'Max traversal depth', '2')
    .option('--wiki', 'Include related wiki entries')
    .option('--json', 'Output as JSON')
    .action(async (nodeId: string, opts) => {
      const depth = Number(opts.depth) || 2;
      const { adapter } = await requireCodeGraph();
      try {
        const resolved = await adapter.resolveNode(nodeId);
        if (!resolved) {
          console.error(`Node not found: ${nodeId}`);
          process.exit(1);
        }

        const callers = await adapter.getCallers(nodeId, depth);
        const callees = await adapter.getCallees(nodeId, depth);
        const fileSiblings = resolved.filePath
          ? (await adapter.getNodesInFile(resolved.filePath)).filter((n: any) => n.id !== resolved.id) // eslint-disable-line @typescript-eslint/no-explicit-any
          : [];
        const wikiMatches = opts.wiki
          ? await findRelatedWikiEntries(nodeId, resolved.filePath)
          : [];

        if (opts.json) {
          console.log(JSON.stringify({
            node: {
              id: resolved.id, kind: resolved.kind, name: resolved.name,
              filePath: resolved.filePath, signature: resolved.signature,
              startLine: resolved.startLine, endLine: resolved.endLine,
              isExported: resolved.isExported,
            },
            callers: callers.map((c: any) => ({ // eslint-disable-line @typescript-eslint/no-explicit-any
              id: c.node.id, kind: c.node.kind, name: c.node.name,
              filePath: c.node.filePath, edgeKind: c.edge?.kind ?? 'calls',
            })),
            callees: callees.map((c: any) => ({ // eslint-disable-line @typescript-eslint/no-explicit-any
              id: c.node.id, kind: c.node.kind, name: c.node.name,
              filePath: c.node.filePath, edgeKind: c.edge?.kind ?? 'calls',
            })),
            fileSiblings: fileSiblings.map((n: any) => ({ // eslint-disable-line @typescript-eslint/no-explicit-any
              id: n.id, kind: n.kind, name: n.name,
            })),
            wiki: wikiMatches,
            engine: 'codegraph',
          }, null, 2));
          return;
        }

        console.log(`Node: ${resolved.id}`);
        console.log(`  Kind:       ${resolved.kind}`);
        console.log(`  Name:       ${resolved.name}`);
        if (resolved.filePath) console.log(`  File:       ${resolved.filePath}:${resolved.startLine}-${resolved.endLine}`);
        if (resolved.signature) console.log(`  Signature:  ${truncate(resolved.signature, 80)}`);
        if (resolved.isExported) console.log(`  Exported:   yes`);

        if (callers.length > 0) {
          console.log('');
          console.log(`Callers (${callers.length}, depth ${depth}):`);
          for (const { node: c, edge } of callers) {
            console.log(`  [${c.kind}] ${c.id} --${edge?.kind ?? 'calls'}-->`);
            if (c.signature) console.log(`    ${truncate(c.signature, 70)}`);
          }
        }

        if (callees.length > 0) {
          console.log('');
          console.log(`Callees (${callees.length}, depth ${depth}):`);
          for (const { node: c, edge } of callees) {
            console.log(`  --${edge?.kind ?? 'calls'}--> [${c.kind}] ${c.id}`);
            if (c.signature) console.log(`    ${truncate(c.signature, 70)}`);
          }
        }

        if (fileSiblings.length > 0) {
          console.log('');
          console.log(`File siblings in ${resolved.filePath} (${fileSiblings.length}):`);
          for (const s of fileSiblings) {
            console.log(`  [${s.kind}] ${s.id} -- ${s.name}`);
          }
        }

        if (wikiMatches.length > 0) {
          console.log('');
          console.log(`Related wiki entries (${wikiMatches.length}):`);
          for (const w of wikiMatches) {
            console.log(`  [${w.type}] ${w.id} -- ${w.title} (${w.matchReason})`);
          }
        }
      } finally {
        adapter.close();
      }
    });

  // ── impact ─────────────────────────────────────────────────────────
  kg
    .command('impact <node-id>')
    .description('Show transitive impact radius (legacy, requires SQLite index)')
    .option('--depth <n>', 'Max depth', '3')
    .option('--json', 'Output as JSON')
    .action((nodeId: string, opts) => {
      const { conn, queries } = openSqliteOrExit();
      try {
        const traverser = new GraphTraverser(queries);
        const subgraph = traverser.getImpactRadius(nodeId, Number(opts.depth) || 3);

        if (opts.json) {
          const nodes = [...subgraph.nodes.values()].map(n => ({
            id: n.id, kind: n.kind, name: n.name, filePath: n.filePath,
          }));
          console.log(JSON.stringify({ nodeCount: nodes.length, edgeCount: subgraph.edges.length, nodes }, null, 2));
          return;
        }

        console.log(`Impact radius for ${nodeId}: ${subgraph.nodes.size} nodes, ${subgraph.edges.length} edges`);
        for (const node of subgraph.nodes.values()) {
          if (node.id === nodeId) continue;
          console.log(`  [${node.kind}] ${node.id}`);
        }
      } finally {
        conn.close();
      }
    });

  // ── dead-code ──────────────────────────────────────────────────────
  kg
    .command('dead-code')
    .description('Find unreferenced symbols (legacy, requires SQLite index)')
    .option('--kinds <kinds>', 'Comma-separated node kinds to check', 'function,method,class')
    .option('--json', 'Output as JSON')
    .action((opts) => {
      const { conn, queries } = openSqliteOrExit();
      try {
        const kinds = opts.kinds.split(',').map((k: string) => k.trim());
        const manager = new GraphQueryManager(queries);
        const deadCode = manager.findDeadCode(kinds);

        if (opts.json) {
          console.log(JSON.stringify(deadCode.map(n => ({
            id: n.id, kind: n.kind, name: n.name, filePath: n.filePath,
            startLine: n.startLine, signature: n.signature,
          })), null, 2));
          return;
        }

        console.log(`Dead code (${deadCode.length} unreferenced symbols):`);
        for (const node of deadCode) {
          console.log(`  [${node.kind}] ${node.name} — ${node.filePath}:${node.startLine}`);
        }
      } finally {
        conn.close();
      }
    });

  // ── cycles ─────────────────────────────────────────────────────────
  kg
    .command('cycles')
    .description('Find circular import dependencies (legacy, requires SQLite index)')
    .option('--json', 'Output as JSON')
    .action((opts) => {
      const { conn, queries } = openSqliteOrExit();
      try {
        const manager = new GraphQueryManager(queries);
        const cycles = manager.findCircularDependencies();

        if (opts.json) {
          console.log(JSON.stringify(cycles, null, 2));
          return;
        }

        if (cycles.length === 0) {
          console.log('No circular dependencies detected.');
          return;
        }

        console.log(`Circular dependencies (${cycles.length}):`);
        for (let i = 0; i < cycles.length; i++) {
          console.log(`  Cycle ${i + 1}: ${cycles[i].join(' → ')} → ${cycles[i][0]}`);
        }
      } finally {
        conn.close();
      }
    });

  // ── migrate ────────────────────────────────────────────────────────
  kg
    .command('migrate')
    .description('Convert JSON knowledge graph to SQLite')
    .option('--json', 'Output result as JSON')
    .action((opts) => {
      const jsonPath = resolve('.workflow', 'codebase', 'knowledge-graph.json');
      if (!existsSync(jsonPath)) {
        console.error(`JSON graph not found: ${jsonPath}`);
        console.error('  Hint: run "maestro kg index" to generate a JSON graph first');
        process.exit(1);
      }

      console.log('Migrating JSON graph to SQLite ...');
      const result = migrateJsonToSqlite(jsonPath);

      if (opts.json) {
        console.log(JSON.stringify(result, null, 2));
        return;
      }

      console.log(`Migrated: ${result.nodes} nodes, ${result.edges} edges`);
      console.log(`Written to: ${result.dbPath}`);
    });

  // ── sync-all ────────────────────────────────────────────────────────
  kg
    .command('sync-all')
    .description('Sync MaestroGraph — all sources (code + domain + spec + knowhow + issues)')
    .option('--full', 'Full rebuild (ignore file hashes)')
    .option('--source <sources>', 'Comma-separated: domain,spec,knowhow,codebase,issue,codegraph')
    .option('--json', 'Output as JSON')
    .action(async (opts) => {
      try {
        const { syncKnowledgeGraph } = await import('../graph/kg/extraction/orchestrator.js');
        const projectRoot = resolve('.');
        const sources = opts.source ? opts.source.split(',').map((s: string) => s.trim()) : undefined;

        console.log('Syncing MaestroGraph (all knowledge sources)...');
        const results = await syncKnowledgeGraph(projectRoot, {
          full: opts.full,
          sources,
        });

        if (opts.json) {
          console.log(JSON.stringify(results, null, 2));
          return;
        }

        let totalNodes = 0;
        let totalEdges = 0;
        for (const r of results) {
          totalNodes += r.nodesAdded;
          totalEdges += r.edgesAdded;
          console.log(`  ${r.source}: +${r.nodesAdded} nodes, +${r.edgesAdded} edges (${r.durationMs}ms)`);
        }
        console.log(`\nTotal: ${totalNodes} nodes, ${totalEdges} edges`);
      } catch (err) {
        console.error('MaestroGraph sync failed:', err instanceof Error ? err.message : err);
        process.exit(1);
      }
    });

  // ── export-json ────────────────────────────────────────────────────
  kg
    .command('export-json')
    .description('Export SQLite graph as JSON')
    .option('--out <path>', 'Output path', '.workflow/codebase/knowledge-graph-export.json')
    .action((opts) => {
      const dbPath = getDatabasePath();
      if (!existsSync(dbPath)) {
        console.error(`SQLite graph not found: ${dbPath}`);
        process.exit(1);
      }

      console.log('Exporting SQLite graph to JSON ...');
      const graph = exportSqliteToJson(dbPath);
      const outPath = resolve(opts.out);
      const outDir = resolve(outPath, '..');
      mkdirSync(outDir, { recursive: true });
      writeFileSync(outPath, JSON.stringify(graph, null, 2), 'utf-8');
      console.log(`Exported: ${graph.nodes.length} nodes, ${graph.edges.length} edges`);
      console.log(`Written to: ${outPath}`);
    });
}
