/**
 * Knowledge Graph Command — CLI for querying codebase knowledge graphs.
 *
 * Subcommands: stats, query, explain, path, diff, diff-wiki
 *
 * Operates on `.workflow/codebase/knowledge-graph.json` generated by
 * compatible code analyzers.
 */

import type { Command } from 'commander';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { execSync } from 'node:child_process';
import type { KnowledgeGraph, GraphNode } from '../graph/types.js';
import { loadGraph } from '../graph/loader.js';
import { searchNodes, findPath, diffChanges, countBy, truncate } from '../graph/query.js';
import { FsAnalyzer } from '../graph/analyzers/fs-analyzer.js';

import { WikiIndexer } from '#maestro-dashboard/wiki/wiki-indexer.js';
import type { WikiEntry } from '#maestro-dashboard/wiki/wiki-types.js';

function loadGraphOrExit(): KnowledgeGraph {
  try {
    return loadGraph();
  } catch (err) {
    console.error((err as Error).message);
    console.error('  Hint: generate one with a compatible code analyzer');
    process.exit(1);
  }
}

// ── Wiki cross-reference ──────────────────────────────────────────────

let _wikiIndexer: WikiIndexer | null = null;
function getWikiIndexer(): WikiIndexer | null {
  if (_wikiIndexer) return _wikiIndexer;
  const workflowRoot = resolve('.workflow');
  if (!existsSync(workflowRoot)) return null;
  _wikiIndexer = new WikiIndexer({ workflowRoot });
  return _wikiIndexer;
}

interface WikiMatch {
  id: string;
  type: string;
  title: string;
  matchReason: string;
}

async function findRelatedWikiEntries(nodeId: string, filePath?: string): Promise<WikiMatch[]> {
  const indexer = getWikiIndexer();
  if (!indexer) return [];
  try {
    const index = await indexer.get();
    const matches: WikiMatch[] = [];
    const seen = new Set<string>();

    for (const e of index.entries) {
      if (seen.has(e.id)) continue;
      if (e.ext?.virtualKind === 'kg-node' && e.ext?.kgNodeId === nodeId) {
        seen.add(e.id);
        matches.push({ id: e.id, type: e.type, title: e.title, matchReason: 'kg-node-entry' });
        continue;
      }
      if (filePath && Array.isArray(e.ext?.codeLocations)) {
        const locs = e.ext.codeLocations as string[];
        const normFp = filePath.replace(/\\/g, '/').toLowerCase();
        if (locs.some(l => l.replace(/\\/g, '/').toLowerCase() === normFp)) {
          seen.add(e.id);
          matches.push({ id: e.id, type: e.type, title: e.title, matchReason: 'codePath-match' });
        }
      }
      if (seen.has(e.id)) continue;
      if (filePath && Array.isArray(e.ext?.codePaths)) {
        const paths = e.ext.codePaths as string[];
        const normFp = filePath.replace(/\\/g, '/').toLowerCase();
        if (paths.some(p => p.replace(/\\/g, '/').toLowerCase() === normFp)) {
          seen.add(e.id);
          matches.push({ id: e.id, type: e.type, title: e.title, matchReason: 'codePath-match' });
        }
      }
    }
    return matches;
  } catch {
    return [];
  }
}

// ── Registration ───────────────────────────────────────────────────────

export function registerKgCommand(program: Command): void {
  const kg = program
    .command('kg')
    .description('Query codebase knowledge graph (.workflow/codebase/knowledge-graph.json)');

  // ── stats ──────────────────────────────────────────────────────────
  kg
    .command('stats')
    .description('Display knowledge graph statistics')
    .option('--json', 'Output as JSON')
    .action((_opts) => {
      const graph = loadGraphOrExit();
      const nodesByType = countBy(graph.nodes, n => n.type);
      const edgesByType = countBy(graph.edges, e => e.type);

      const data = {
        project: graph.project.name,
        version: graph.version,
        nodes: { total: graph.nodes.length, byType: nodesByType },
        edges: { total: graph.edges.length, byType: edgesByType },
        layers: graph.layers.length,
        tourSteps: graph.tour.length,
      };

      if (_opts.json) {
        console.log(JSON.stringify(data, null, 2));
        return;
      }

      console.log(`Knowledge Graph: ${data.project} (v${data.version})`);
      console.log('');
      console.log(`Nodes: ${data.nodes.total}`);
      for (const [type, count] of Object.entries(nodesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Edges: ${data.edges.total}`);
      for (const [type, count] of Object.entries(edgesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Layers: ${data.layers}`);
      console.log(`Tour steps: ${data.tourSteps}`);
    });

  // ── query ──────────────────────────────────────────────────────────
  kg
    .command('query <text>')
    .description('Search nodes by name, summary, or tags')
    .option('--limit <n>', 'Max results', '10')
    .option('--type <nodeType>', 'Filter by node type')
    .option('--json', 'Output as JSON')
    .action((text: string, opts) => {
      const graph = loadGraphOrExit();
      const limit = Number(opts.limit) || 10;
      const matches = searchNodes(graph, text, { limit, type: opts.type });
      const total = searchNodes(graph, text, { limit: Infinity, type: opts.type }).length;

      if (opts.json) {
        console.log(JSON.stringify({ query: text, total, nodes: matches }, null, 2));
        return;
      }

      console.log(`Query: "${text}"  (${matches.length}/${total} results)`);
      for (const n of matches) {
        console.log(`  [${n.type}] ${n.id} -- ${truncate(n.summary, 80)}`);
      }
    });

  // ── explain ────────────────────────────────────────────────────────
  kg
    .command('explain <node-id>')
    .description('Show full details of a node and its connections')
    .option('--json', 'Output as JSON')
    .option('--no-wiki', 'Skip wiki cross-reference lookup')
    .action(async (nodeId: string, opts) => {
      const graph = loadGraphOrExit();
      const node = graph.nodes.find(n => n.id === nodeId);

      if (!node) {
        console.error(`Node not found: ${nodeId}`);
        process.exit(1);
      }

      const incoming = graph.edges.filter(e => e.target === nodeId);
      const outgoing = graph.edges.filter(e => e.source === nodeId);
      const layers = graph.layers.filter(l => l.nodeIds.includes(nodeId));

      const wikiMatches = opts.wiki !== false
        ? await findRelatedWikiEntries(nodeId, node.filePath)
        : [];

      if (opts.json) {
        console.log(JSON.stringify({ node, incoming, outgoing, layers, wiki: wikiMatches }, null, 2));
        return;
      }

      console.log(`Node: ${node.id}`);
      console.log(`  Type:       ${node.type}`);
      console.log(`  Name:       ${node.name}`);
      if (node.filePath) console.log(`  File:       ${node.filePath}`);
      console.log(`  Summary:    ${node.summary}`);
      if (node.tags?.length) console.log(`  Tags:       ${node.tags.join(', ')}`);
      if (node.complexity) console.log(`  Complexity: ${node.complexity}`);

      if (layers.length > 0) {
        console.log('');
        console.log('Layers:');
        for (const l of layers) {
          console.log(`  ${l.id} -- ${l.name}`);
        }
      }

      if (incoming.length > 0) {
        console.log('');
        console.log(`Incoming edges (${incoming.length}):`);
        for (const e of incoming) {
          console.log(`  ${e.source} --${e.type}--> ${nodeId}`);
        }
      }

      if (outgoing.length > 0) {
        console.log('');
        console.log(`Outgoing edges (${outgoing.length}):`);
        for (const e of outgoing) {
          console.log(`  ${nodeId} --${e.type}--> ${e.target}`);
        }
      }

      if (wikiMatches.length > 0) {
        console.log('');
        console.log(`Related wiki entries (${wikiMatches.length}):`);
        for (const w of wikiMatches) {
          console.log(`  [${w.type}] ${w.id} -- ${w.title} (${w.matchReason})`);
        }
      }
    });

  // ── path ───────────────────────────────────────────────────────────
  kg
    .command('path <from-id> <to-id>')
    .description('Find shortest path between two nodes (BFS, undirected)')
    .option('--json', 'Output as JSON')
    .action((fromId: string, toId: string, opts) => {
      const graph = loadGraphOrExit();

      try {
        const result = findPath(graph, fromId, toId);

        if (!result.found) {
          if (opts.json) {
            console.log(JSON.stringify({ from: fromId, to: toId, path: null, message: 'No path found' }, null, 2));
          } else {
            console.log(`No path found from ${fromId} to ${toId}`);
          }
          return;
        }

        if (opts.json) {
          console.log(JSON.stringify({ from: fromId, to: toId, length: result.length, steps: result.steps }, null, 2));
          return;
        }

        console.log(`Path: ${fromId} -> ${toId}  (${result.length} hops)`);
        console.log('');
        for (let i = 0; i < result.steps.length; i++) {
          const step = result.steps[i];
          console.log(`  [${step.type ?? '?'}] ${step.node} -- ${truncate(step.name ?? '', 60)}`);
          if (step.edgeToNext) {
            console.log(`    | ${step.edgeToNext}`);
          }
        }
      } catch (err) {
        console.error((err as Error).message);
        process.exit(1);
      }
    });

  // ── diff ───────────────────────────────────────────────────────────
  kg
    .command('diff')
    .description('Show KG nodes affected by git changes')
    .option('--staged', 'Use staged changes only')
    .option('--json', 'Output as JSON')
    .action((opts) => {
      const graph = loadGraphOrExit();

      let changedFiles: string[];
      try {
        const cmd = opts.staged
          ? 'git diff --staged --name-only'
          : 'git diff --name-only';
        const output = execSync(cmd, { encoding: 'utf-8' }).trim();
        changedFiles = output ? output.split('\n').map(f => f.trim()).filter(Boolean) : [];
      } catch {
        console.error('Failed to run git diff. Are you in a git repository?');
        process.exit(1);
      }

      if (changedFiles.length === 0) {
        if (opts.json) {
          console.log(JSON.stringify({ changedFiles: [], direct: [], impacted: [] }, null, 2));
        } else {
          console.log('No changed files detected.');
        }
        return;
      }

      const result = diffChanges(graph, changedFiles);

      if (opts.json) {
        console.log(JSON.stringify(result, null, 2));
        return;
      }

      console.log(`Changed files: ${changedFiles.length}`);
      console.log('');

      console.log(`Direct (${result.direct.length}):`);
      if (result.direct.length === 0) {
        console.log('  (no KG nodes match changed files)');
      } else {
        for (const n of result.direct) {
          console.log(`  [${n.type}] ${n.id} -- ${truncate(n.summary, 60)}`);
        }
      }

      console.log('');
      console.log(`Impacted (${result.impacted.length}):`);
      if (result.impacted.length === 0) {
        console.log('  (no 1-hop neighbors found)');
      } else {
        for (const n of result.impacted) {
          console.log(`  [${n.type}] ${n.id} -- ${truncate(n.summary, 60)}`);
        }
      }
    });

  // ── diff-wiki ─────────────────────────────────────────────────────
  kg
    .command('diff-wiki')
    .description('Cross-reference git changes with KG nodes and wiki entries')
    .option('--staged', 'Use staged changes only')
    .option('--json', 'Output as JSON')
    .action(async (opts) => {
      const graph = loadGraphOrExit();

      let changedFiles: string[];
      try {
        const cmd = opts.staged
          ? 'git diff --staged --name-only'
          : 'git diff --name-only';
        const output = execSync(cmd, { encoding: 'utf-8' }).trim();
        changedFiles = output ? output.split('\n').map(f => f.trim()).filter(Boolean) : [];
      } catch {
        console.error('Failed to run git diff. Are you in a git repository?');
        process.exit(1);
      }

      if (changedFiles.length === 0) {
        if (opts.json) {
          console.log(JSON.stringify({ changedFiles: [], affectedWiki: [] }, null, 2));
        } else {
          console.log('No changed files detected.');
        }
        return;
      }

      const result = diffChanges(graph, changedFiles);

      // Collect all affected file paths from KG nodes
      const affectedPaths = new Set<string>();
      for (const n of result.direct) {
        if (n.filePath) affectedPaths.add(n.filePath.replace(/\\/g, '/').toLowerCase());
      }
      for (const n of result.impacted) {
        if (n.filePath) affectedPaths.add(n.filePath.replace(/\\/g, '/').toLowerCase());
      }
      for (const f of changedFiles) {
        affectedPaths.add(f.replace(/\\/g, '/').toLowerCase());
      }

      // Cross-reference with wiki
      const indexer = getWikiIndexer();
      const affectedWiki: Array<{ id: string; type: string; title: string; reason: string }> = [];

      if (indexer) {
        try {
          const index = await indexer.get();
          const seen = new Set<string>();
          for (const entry of index.entries) {
            if (seen.has(entry.id)) continue;
            if (Array.isArray(entry.ext?.codeLocations)) {
              const locs = entry.ext.codeLocations as string[];
              for (const loc of locs) {
                if (affectedPaths.has(loc.replace(/\\/g, '/').toLowerCase())) {
                  seen.add(entry.id);
                  affectedWiki.push({ id: entry.id, type: entry.type, title: entry.title, reason: 'codeLocation' });
                  break;
                }
              }
            }
            if (seen.has(entry.id)) continue;
            if (Array.isArray(entry.ext?.codePaths)) {
              const paths = entry.ext.codePaths as string[];
              for (const p of paths) {
                if (affectedPaths.has(p.replace(/\\/g, '/').toLowerCase())) {
                  seen.add(entry.id);
                  affectedWiki.push({ id: entry.id, type: entry.type, title: entry.title, reason: 'codePath' });
                  break;
                }
              }
            }
          }
        } catch { /* wiki unavailable — continue without */ }
      }

      if (opts.json) {
        console.log(JSON.stringify({
          changedFiles,
          directNodes: result.direct.length,
          impactedNodes: result.impacted.length,
          affectedWiki,
        }, null, 2));
        return;
      }

      console.log(`Changed files: ${changedFiles.length}`);
      console.log(`KG direct: ${result.direct.length}, impacted: ${result.impacted.length}`);
      console.log('');

      if (affectedWiki.length === 0) {
        console.log('No wiki entries affected by these changes.');
      } else {
        console.log(`Affected wiki entries (${affectedWiki.length}):`);
        for (const w of affectedWiki) {
          console.log(`  [${w.type}] ${w.id} -- ${w.title} (${w.reason})`);
        }
      }
    });

  // ── index ─────────────────────────────────────────────────────────
  kg
    .command('index')
    .description('Scan codebase and generate knowledge graph')
    .option('--src <path>', 'Source directory to scan', 'src')
    .option('--json', 'Output stats as JSON after indexing')
    .action(async (opts) => {
      const srcPath = resolve(opts.src);
      if (!existsSync(srcPath)) {
        console.error(`Source directory not found: ${srcPath}`);
        process.exit(1);
      }

      const analyzer = new FsAnalyzer();
      console.log(`Scanning ${srcPath} ...`);

      const graph = await analyzer.analyze(srcPath);

      // If scanning a subdirectory, try to pick up project name from CWD
      const cwdPkg = resolve('package.json');
      if (existsSync(cwdPkg) && srcPath !== resolve('.')) {
        try {
          const pkg = JSON.parse(readFileSync(cwdPkg, 'utf-8'));
          if (pkg.name) graph.project.name = pkg.name;
          // Also pick up frameworks from root package.json
          const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
          const fwChecks: [string, string][] = [
            ['react', 'React'], ['vue', 'Vue'], ['angular', 'Angular'],
            ['express', 'Express'], ['fastify', 'Fastify'], ['next', 'Next.js'],
            ['nuxt', 'Nuxt'], ['commander', 'Commander'], ['ink', 'Ink'],
          ];
          const frameworks: string[] = [];
          for (const [dep, name] of fwChecks) {
            if (allDeps?.[dep]) frameworks.push(name);
          }
          if (frameworks.length > 0) graph.project.frameworks = frameworks;
        } catch { /* ignore */ }
      }

      // Ensure output directory exists
      const outDir = resolve('.workflow', 'codebase');
      mkdirSync(outDir, { recursive: true });

      const outPath = resolve(outDir, 'knowledge-graph.json');
      writeFileSync(outPath, JSON.stringify(graph, null, 2), 'utf-8');

      // Collect stats
      const nodesByType: Record<string, number> = {};
      for (const n of graph.nodes) {
        nodesByType[n.type] = (nodesByType[n.type] ?? 0) + 1;
      }
      const edgesByType: Record<string, number> = {};
      for (const e of graph.edges) {
        edgesByType[e.type] = (edgesByType[e.type] ?? 0) + 1;
      }

      const stats = {
        project: graph.project.name,
        languages: graph.project.languages,
        frameworks: graph.project.frameworks,
        nodes: { total: graph.nodes.length, byType: nodesByType },
        edges: { total: graph.edges.length, byType: edgesByType },
        layers: graph.layers.length,
        tourSteps: graph.tour.length,
        output: outPath,
      };

      if (opts.json) {
        console.log(JSON.stringify(stats, null, 2));
        return;
      }

      console.log('');
      console.log(`Project: ${stats.project}`);
      console.log(`Languages: ${stats.languages.join(', ') || 'none detected'}`);
      if (stats.frameworks.length > 0) {
        console.log(`Frameworks: ${stats.frameworks.join(', ')}`);
      }
      console.log('');
      console.log(`Nodes: ${stats.nodes.total}`);
      for (const [type, count] of Object.entries(nodesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Edges: ${stats.edges.total}`);
      for (const [type, count] of Object.entries(edgesByType)) {
        console.log(`  ${type}: ${count}`);
      }
      console.log('');
      console.log(`Layers: ${stats.layers}`);
      console.log(`Tour steps: ${stats.tourSteps}`);
      console.log('');
      console.log(`Written to: ${outPath}`);
    });
}
